services:
    bot:
        build: .
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            - db
        networks:
            - backend

    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: espresso
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend

volumes:
    pgdata:

networks:
    backend:
        driver: bridge
