services:
    bot:
        build: .
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend

    db:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - 5432:5432
        env_file:
            - .env
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
            interval: 10s
            timeout: 5s
            retries: 5

    studio:
        build: .
        ports:
            - 4983:4983
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
        command: bun drizzle-kit studio --host=0.0.0.0 --port 4983
        networks:
            - backend

volumes:
    pgdata:

networks:
    backend:
        driver: bridge
