services:
    bot:
        build: .
        env_file:
            - .env
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy
        networks:
            - backend
        secrets:
            - postgres_user
            - postgres_pass
            - postgres_name

    db:
        image: postgres:latest
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER_FILE: /run/secrets/postgres_user
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
            POSTGRES_DB_FILE: /run/secrets/postgres_name
        volumes:
            - pgdata:/var/lib/postgresql/data
        secrets:
            - postgres_user
            - postgres_pass
            - postgres_name
        networks:
            - backend
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user) -d $(cat /run/secrets/postgres_name)"]
            interval: 10s
            timeout: 5s
            retries: 5

    studio:
        build: .
        ports:
            - 4983:4983
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
        command: bun drizzle-kit studio --host=0.0.0.0 --port 4983
        networks:
            - backend

volumes:
    pgdata:

networks:
    backend:
        driver: bridge

secrets:
    postgres_user:
        file: ./secrets/postgres_user.txt
    postgres_pass:
        file: ./secrets/postgres_pass.txt
    postgres_name:
        file: ./secrets/postgres_name.txt
